server:
  port: 3344


spring:
  application:
    name: springCloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1033261847/springcloud-config
          #uri: git@github.com:1033261847/springcloud-config.git #github 仓库路径
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false